mybatis:
  mapperLocations: classpath:mappers/*.xml
  configLocation: classpath:mybatis-config.xml

config:
  env: dev

spring:
  aop:
    auto: true
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates/

jdbc:
  demo:
    name: demo
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

server:
  port: 8081